environment:
  matrix:
  - python: 27
  - python: 27-x64
  - python: 35
  - python: 35-x64
  - python: 36
  - python: 36-x64
  - python: 37
  - python: 37-x64
  - python: 38
  - python: 38-x64

install:
  - SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%
  - python -m pip install -U pip wheel setuptools

build: off
build_script:
  - python setup.py bdist_wheel

test: off
test_script:
  - pip install -r requirements-test.txt
  - pip install xmlsec --only-binary=xmlsec --no-index --find-links=dist
  - pytest -v --color=yes
  - ps: Get-ChildItem dist\*.whl | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
