sudo: false
language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'

addons:
  apt:
    packages:
        libxmlsec1
        libxmlsec1-dev
        libxmlsec1-openssl
        pkg-config

install:
  - 'travis_retry pip install -e ".[test]" --use-mirrors'

script: 'py.test'
