dist: trusty
sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
addons:
  apt:
    packages:
    - libssl-dev
    - libxmlsec1
    - libxmlsec1-dev
    - libxmlsec1-openssl
    - libxslt1-dev
    - pkg-config
install:
- travis_retry pip install -r requirements-test.txt
- travis_retry pip install -e "."
- pip list
script: py.test tests
deploy:
  provider: pypi
  user: bgaifullin
  password:
    secure: wuWADHAmAz2e2wMMVadhDXh5UMqtYLM7NjzjT4LVojPzbI+04BHFjmUVDEe3nOtxiEv/oJuumutb24MNMppSRklmofy/jqyDwEEPwsNJWvLi8eK60AohAhmP5rU1Vp5B6azotWnDiVApL18t9+nJqL+6nEQ5dcQeu0jtskiC5EOaIMgB12+HHfV9QUHYsQp9t+4LMsM8TaIogom3DSMUaKTRHdWbcmHgmYF3JJTNPDyUkND8zr1bwezf/jb9ytRVzo/mQh0tsHQF80CdkC9Cu3rXxgnE0RUrU9gC2Nwyj4UZQOxhXXQpd55HEGE00jUscaiDCc6D4Y4NGZ2gu1l4lx2z3UyvV3YdaZMPg8FSCJ1Z6TuwDYAZl3WdIvidiDKU1Pj/YyP8RAMmNhmLpgZNsK9iQ3o9wNFgr0w4rutg1vJUVOgu5nEBVBqERX8YXIsoq7eSMIdJxiVA6sralxJLxGsmNhtxpxgr0UJKx12tnJCgZnDtquwObaPzeEoAkqWsxu5fDyxGRlB4UCMn2ZckdWkjRpjymiScgVWM+3N9x6pwD+9/EsR6N4S1zVIghjGmEkOm5yeiQr11T9ZQjDtFA7sap02a9d4jmxEk6EZW4KoBWTgFOs9/qb3YH79PGNVok/HjuctLLl/udVkD8JSYPUjCGSx08kdr1TCGTJSRGUQ=
  on:
    tags: true
    branch: master
