language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'

addons:
  apt:
    packages:
      - libxslt1-dev
      - libssl-dev
      - libxmlsec1-dev

install:
  - travis_retry pip install -e ".[test]"

script: py.test
