dist: trusty
sudo: false
language: python
notifications:
  email: false
matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: required
addons:
  apt:
    packages:
    - libssl-dev
    - libxmlsec1
    - libxmlsec1-dev
    - libxmlsec1-openssl
    - libxslt1-dev
    - pkg-config
before_install:
- echo "${TRAVIS_TAG:-1.0.1.dev}" >version.txt
install:
- travis_retry pip install -r requirements-test.txt
- travis_retry pip install -e "."
- pip list
script: py.test -v tests
before_deploy:
- travis_retry pip install Sphinx
- python setup.py build_sphinx
deploy:
  skip_cleanup: true
  skip_upload_docs: false
  provider: pypi
  user: mehcode
  on:
    tags: true
    distributions: sdist bdist_wheel
    python: '2.7'
  password:
    secure: KNBbGaiAWirptxcuLjqNVgQ9E3jc75kj2+A5MRh+XvDVf6xFLAhrNg0+p/a3d+Tdap4/W5retxDdafLoMJ80ftyJFWV+lnrDxBhcrT686HGXPb0FCn58+Mho0RhM7CSHJIM8E85pVUV5E6QrmgmNWG8KKEaF3Vs5RJBhlP/g7Bg=
