dist: trusty
sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'

addons:
  apt:
    packages:
      - libssl-dev
      - libxmlsec1
      - libxmlsec1-dev
      - libxmlsec1-openssl
      - libxslt1-dev
      - pkg-config

install:
  - travis_retry pip install -r requirements-test.txt
  - travis_retry pip install -e "."
  - pip list

script: 'py.test tests'
